version: '3'
services:
  bot:
    build: .
    env_file:
      - .env
    networks:
      nginx_net:
    restart: always
    ports:
      - "8006:8000"  # ngrok перенаправляет на этот порт

networks:
  nginx_net:
    name: nginx_net
